name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK }}
          PORT: 8000
        run: |
          if [[ -z "$DEPLOY_URL" ]]; then
            echo "Error: DEPLOY_URL is not set. Check your GitHub Secrets."
            exit 1
          fi
          curl -X POST "$DEPLOY_URL"
